spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/lavandinas
    username: lavandinas
    password: lavandinas2020
