spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        id:
          new_generator_mappings: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/lavandinas
    username: lavandinas
    password: lavandinas2020
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: lavandinas.medellin@gmail.com
#    password: Zaq12wsX
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls: true
